config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'login', to: 'home#show'
  post 'login', to: 'sessions#create'

  resources :users, only: [:new, :create]

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"

  namespace :api, defaults: { format: :json } do
    resources :users, only: [ :update, :show ]
  end

  get '/games', to: 'games#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  before_save :default_chip_count

  def self.from_omniauth(auth)
   where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
     user.provider = auth.provider
     user.uid = auth.uid
     user.first_name = auth.info.first_name
     user.last_name = auth.info.last_name
     user.email = auth.info.email
     user.password = 'password'
     user.oauth_token = auth.credentials.token
     user.oauth_expires_at = Time.at(auth.credentials.expires_at)
     user.save!
   end
  end

  def default_chip_count
    self.chips ||= 0
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  protect_from_forgery with: :null_session
  def show

    @user = User.find(params[:id])
  end

  def update
    # binding.pry
    @user = User.find(params[:id])

    @user.update_attributes(user_params)

  end

  private
    def user_params
      params.require(:user).permit(:chips)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_current_user
    render file: "/public/404" unless current_user
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :require_current_user


  def index
    @user = current_user
  end

  def show
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if params[:provider].present?
      user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
      redirect_to games_path
    else
      @user = User.find_by(email: params[:session][:email])
      verify_user
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

    def verify_user
      if @user && @user.authenticate(params[:session][:password])
        login_successful
      else
        flash[:failure] = "That login was unsuccessful"
        redirect_to login_path
      end
    end

    def login_successful
      session[:user_id] = @user.id
      redirect_to games_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/games/index.html.erb
<%= javascript_pack_tag 'application' %>
<%= stylesheet_pack_tag 'application' %>
<%= content_tag :div,
  id: "user_data",
  data: @user.to_json do %>
 <% end %>

app/views/home/show.html.erb
    <%= stylesheet_link_tag    'home', media: 'all', 'data-turbolinks-track': 'reload' %>








<h1 class="title">Welcome to BlackJack!</h1>

<section class="login">
  <h2 >Login</h2>
  <%= form_for(:session, url: login_path) do |f| %>
  <div class="email">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="password">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

    <%= f.submit "Login" %>


  <% end %>
<div class="link1">
  <%= link_to "Create Account", new_user_path  %><br>
</div>
<div class="link2">
  <%= link_to image_tag("google.png"), "/auth/google_oauth2", id: "sign_in" %>
</div>


</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blackjack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <% if current_user %>
        Signed in as <strong><%= current_user.first_name %></strong>!
        <%= link_to "Sign out", signout_path, id: "sign_out" %>
      <% else %>
        <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
      <% end %>
    </div>
    <div>
    <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<%= stylesheet_link_tag    'new', media: 'all', 'data-turbolinks-track': 'reload' %>


<div class="new">
  <h2>Create New Account</h2>
  <%= form_for @user do |f| %>
  <div class="first-name">
    <%= f.label :first_name  %>
    <%= f.text_field :first_name %>
  </div>
  <div class="last-name">
    <%= f.label :last_name  %>
    <%= f.text_field :last_name %>
  </div>
  <div class="email">
    <%= f.label :email  %>
    <%= f.text_field :email %>
  </div>
  <div class="password">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <%= f.submit "Create Account", :class => 'submit' %>

  <% end %>

</div>